twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        mercure_url: '%env(MERCURE_PUBLIC_URL)%'

when@test:
    twig:
        strict_variables: true
