controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

mercure:
    path: /.well-known/mercure
    controller: symfony\Bundle\MercureBundle\Controller\DiscoveryController
